### PR TITLE
Support uploading to a project UUID

### PR DESCRIPTION
**Pull request by ribbybibby**
Fixes: #2 

I've also removed this line which for reasons I don't understand seems to have been introducing a ~3 minute delay to the Github Action when I was testing it:
```
console.log(`Post data: ${postData}`);
```

### CODE REVIEW

**Comment by stevespringett** [comment]
@coderpatros as the original author, can you review this?

**Comment by ChaosInTheCRD** [comment]
once again 😄  any updates?

**Comment by stevespringett** [comment]
@coderpatros LGTM. Will merge.

**Comment by stevespringett** [comment]
Thanks for the PR @ribbybibby

**Pull request merged**
